apiVersion: kubeadm.k8s.io/v1beta3
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: abcdef.0123456789abcdef
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 192.168.1.5 #master node ip address
  bindPort: 6443
nodeRegistration:
  criSocket: unix:///var/run/containerd/containerd.sock
  imagePullPolicy: IfNotPresent
  # name: rasp-worker-1 #hostname
  taints: null
---
apiServer:
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta3
certificatesDir: /etc/kubernetes/pki
clusterName: rasp-kubernetes
controllerManager: {}
dns: {}
etcd:
  local:
    imageRepository: registry.aliyuncs.com/google_containers #k8s container registry prefix
    dataDir: /var/lib/etcd
imageRepository: registry.aliyuncs.com/google_containers #k8s container registry prefix
kind: ClusterConfiguration
kubernetesVersion: 1.25.0
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/12
  podSubnet: 10.244.0.0/24 # try to solve /run/flannel/subnet.env: no such file or directory
scheduler: {}
